### ISSUE TITLE
購読しているリポジトリを表形式で閲覧したい

### ISSUE THREAD

**Issue by uhooi** [ios-osushi/release-subscriptions#1]
## 概要

現状だと購読しているリポジトリを YAML で管理しているため、行数がかさばって俯瞰しにくい。
表形式で記述して俯瞰しやすくしたい。

## 案

YAML でなく Swift ファイルで管理する。
移植性は下がるが、直接操作できるメリットもある。

Before

```yaml
repositories:
  - kind: primary
    case: releases
    name: Swift
    owner: apple
    repo: swift
  
  - kind: primary
    case: releases
    name: Swift Algorithms
    owner: apple
    repo: swift-algorithms
```

After

```swift
let repositories: Repository = [
    (.primary, .releases, "Swift", "apple", "swift"),
    (.primary, .releases, "Swift Algorithms", "apple", "swift-algorithms"),
]
```

表形式とまでは呼べないが、YAML よりは俯瞰しやすい。
